# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
  - deployment: TestDeployment
    environment: GHRepo
  - job: TestDeploymentjob
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo write your commands here

          echo hello world